from django.urls import path
from . import views
urlpatterns = [
 path('', views.index, name= "books.index"),
 path('list_books/', views.list_books, name= "books.list_books"),
 path('list_books/one_book/', views.viewbook, name="books.one_book"),
 path('aboutus/', views.aboutus, name="books.aboutus"),
 path('html5/links',views.links, name = "books.html5"),
 path('html5/text/formatting', views.formatting, name='formatting'),
 path('html5/listing', views.listing, name='listing'),
 path('html5/tables', views.tables, name='tables'),
 path('search/', views.search, name='search'),
 path('simple/query', views.simple_query, name='simpleQuery'),
 path('complex/query', views.complex_query, name='complexQuery'),
 path('lab8/task1', views.task1, name='task1'),
 path('lab8/task2', views.task2, name='task2'),
 path('lab8/task3', views.task3, name='task3'),
 path('lab8/task4', views.task4, name='task4'),
 path('lab8/task5', views.task5, name='task5'),
 path('lab8/task7', views.task7, name='task7'),
 path('lab10_part1/listbooks', views.list_books_part1, name='listbooks'),
 path('lab10_part1/addbook', views.add_book, name='addbook'),
 path('lab10_part1/editbook/<int:id>/', views.edit_book, name='editbook'),
 path('lab10_part1/deletebook/<int:id>/', views.delete_book, name='deletebook'),
 path('lab9/task1/', views.number_of_students_department, name='l9t1'),
 path('lab9/task2', views.number_of_students_course, name='l9t2'),
 path('lab9/task3', views.oldest, name='l9t3'),
 path('lab9/task4', views.descending, name='l9t4'),
 path('lab10_part2/listbooks', views.list_books_part2, name='listbooks_part2'),
 path('lab10_part2/addbook', views.add_book_part2, name='addbook_part2'),
 path('lab10_part2/editbook/<int:id>/', views.edit_book_part2, name='editbook_part2'),
 path('lab10_part2/deletebook/<int:id>/', views.delete_book_part2, name='deletebook_part2'),
]

